services:
  llama_cpp:
    image: ghcr.io/ggml-org/llama.cpp:${DOCKER_TAG}
    container_name: llama_cpp
    runtime: nvidia
    ports:
      - "${PORT}:8000"
    volumes:
      - ./models:/models
      - ./config/router.sh:/app/router.sh
      - ./config/models.ini:/app/models.ini
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LLAMA_API_KEY=${LLAMA_API_KEY}
    restart: unless-stopped
